### PR TITLE
Allow user to omit wildcard, and add PEM download link.

### PR DESCRIPTION
**Pull request by mrstegeman**
Also, add proper documentation.

### CODE REVIEW

**Comment by mrstegeman** [comment]
Hi Paul,

Thanks for creating this library, it's great! Any chance of getting it
published on PyPi?

-Mike

**Comment by PaulSec** [comment]
Yes, I will get this available on PyPi this week. 
I will keep you posted as soon as it will be up :)

**Comment by PaulSec** [comment]
Hello Mike!
Just to let you know, I pushed crt.sh as a PyPi package [here](https://pypi.python.org/pypi?:action=display&name=crtsh&version=0.1.0)

Cheers!

**Comment by mrstegeman** [comment]
You rock! Thank you.

-Mike

**Comment by PaulSec** [comment]
No worries, thanks to you!
Let me know if you want to improve the lib even more 👍

**Pull request merged**
